export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_FORM_UPDATE = 'LOGIN_FORM_UPDATE'

export const REGISTER = 'REGISTER'
export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'
export const REGISTER_FORM_UPDATE = 'REGISTER_FORM_UPDATE'
